# Generated by Django 4.1 on 2022-08-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0002_video_video_240_video_video_360_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="took_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="original_video",
            field=models.FileField(upload_to="", verbose_name="Original Video"),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_240",
            field=models.FileField(
                blank=True, null=True, upload_to="video240", verbose_name="Video 240"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_360",
            field=models.FileField(
                blank=True, null=True, upload_to="video360", verbose_name="Video 360"
            ),
        ),
    ]
